# -*- coding: utf-8 -*-
"""Sentence Similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADkVqsjNt0f2PRlis0_oWRzki8hUPyvl
"""

pip install -U transformers[sentencepiece] sentence_transformers s3fs

# Load packages
import pandas as pd
import torch
from torch.nn import CosineSimilarity
from torch.nn.functional import normalize
from transformers import AutoTokenizer, AutoModel
from sentence_transformers import util

# Mean pooling
def mean_pooling(model_output,attention_mask):
    token_embeddings = model_output[0]
    attention_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.shape)
    return (token_embeddings * attention_mask_expanded).sum(1) / torch.clamp(attention_mask_expanded.sum(1), min=1e-9)

# Load datasets
PIM_cleaned = pd.read_csv(r's3://s3-sgws-predictive/SGWS_Product_Matching/staging_files/cleaned_data/PIM_CLEANED_DATA.csv', low_memory = False)
train = pd.read_csv(r's3://s3-sgws-predictive/SGWS_Product_Matching/Team/Lukas/Transformers/Datasets/datasets_data_train.csv', low_memory = False)

sequences_retailer = train[train['Match'] == 1]['na_retailer_item_desc'].to_list()
sequences_sgws = PIM_cleaned['SgwsDescription'].to_list()

# Load model
checkpoint = 'sentence-transformers/all-MiniLM-L6-v2'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModel.from_pretrained(checkpoint)

# Tokenize sentences
encoded_input_retailer = tokenizer(sequences_retailer, return_tensors = 'pt', padding = True, truncation = True)
encoded_input_sgws = tokenizer(sequences_sgws, return_tensors = 'pt', padding = True, truncation = True)

model_output_retailer = model(**encoded_input_retailer)

model_output_sgws = model(**encoded_input_sgws)

# Compute token embeddings
with torch.no_grad():
    model_output_retailer = model(**encoded_input_retailer)
    model_output_sgws = model(**encoded_input_sgws)

# Perform mean pooling
sentence_embeddings_retailer = mean_pooling(model_output_retailer,encoded_input_retailer['attention_mask'])
sentence_embeddings_sgws = mean_pooling(model_output_sgws,encoded_input_sgws['attention_mask'])

cosine_scores = util.cos_sim(sentence_embeddings_retailer,sentence_embeddings_sgws)
cosine_scores

# Normalize embeddings
#sentence_embeddings = F.normalize(sentence_embeddings)
#print(sentence_embeddings)

